### ISSUE TITLE
只能驱动255个灯珠

### ISSUE THREAD

**Issue by adadKKKX** [Jack-InGitHub/WS2812#1]
我使用的你的源码 stm32f407VET6 ,发现小问题
# 1
` WS2812_RandColorWipe  WS2812_TheaterChaseRainbow WS2812_SingleBreatheRainbow` 
这几个函数内第一个for的循环次数是256（255）应该是宏`WS2812_NUM`
# 2
WS2812_OneSet 的第一个参数uint8_t 改成更宽可以驱动更多灯珠

**Comment by Jack-InGitHub** [comment]
非常欢迎提交PR, 这个代码比较古老了

**Comment by liupingquan** [comment]
建议创建新branch 用pr的方式提交代码,并注明更改项目和内容 @adadKKKX
